spring.application.name=Lakshya
# Show SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

# Log SQL statements
logging.level.org.hibernate.SQL=DEBUG

# Log bind parameter values (THIS is the key part)
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.open-in-view=false
