spring:
  datasource:
    # Update these 3 lines for local development:
    url: jdbc:postgresql://localhost:5432/lakshya_db
    username: postgres
    password: hello  # REPLACE with your actual local PostgreSQL password
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: false
        useServerPrepStmts: false
        prepStmtCacheSize: 0
        prepStmtCacheSqlLimit: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080