spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.abljgshvqngttswcuwpl
    password: KUnal@333456
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: false
        useServerPrepStmts: false
        prepStmtCacheSize: 0
        prepStmtCacheSqlLimit: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080